CREATE DATABASE RCD;

CREATE TABLE users(
id INT NOT NULL AUTO_INCREMENT ,
username VARCHAR( 16 ) NOT NULL ,
email VARCHAR( 255 ) NOT NULL ,
PASSWORD VARCHAR( 255 ) NOT NULL ,
salt VARCHAR( 255 ) NOT NULL ,
PRIMARY KEY ( id )
)
